package com.authvault.presentation.ui.common

private val ICON_MAP = mapOf(
    "GitHub" to "github",
    "Google" to "google",
    "Facebook" to "facebook",
    "Twitter" to "twitter",
    "X" to "x",
    "Amazon" to "amazon",
    "Microsoft" to "microsoft",
    "Dropbox" to "dropbox",
    "Slack" to "slack",
    "Discord" to "discord",
    "Apple" to "apple",
    "Steam" to "steam",
    "PayPal" to "paypal",
    "GitLab" to "gitlab",
    "Bitbucket" to "bitbucket",
    "Cloudflare" to "cloudflare",
    "Twitch" to "twitch",
    "LinkedIn" to "linkedin",
    "Reddit" to "reddit",
    "Binance" to "binance",
    "Coinbase" to "coinbase",
    "Adobe" to "adobe",
    "Figma" to "figma",
    "Notion" to "notion",
    "Instagram" to "instagram",
    "WhatsApp" to "whatsapp",
    "Telegram" to "telegram",
    "Signal" to "signal",
    "ProtonMail" to "protonmail",
    "Bitwarden" to "bitwarden",
    "LastPass" to "lastpass",
    "Dashlane" to "dashlane",
    "Authy" to "authy",
    "Namecheap" to "namecheap",
    "GoDaddy" to "godaddy",
    "Shopify" to "shopify",
    "Apple ID" to "apple",
    "Netflix" to "netflix",
    "Spotify" to "spotify",
    "Stripe" to "stripe",
    "Heroku" to "heroku",
    "DigitalOcean" to "digitalocean",
    "AWS" to "amazonaws",
    "Azure" to "microsoftazure",
    "Vercel" to "vercel",
    "Netlify" to "netlify",
    "WordPress" to "wordpress",
    "OpenAI" to "openai",
    "Okta" to "okta",
    "Atlassian" to "atlassian",
    "Asana" to "asana",
    "Trello" to "trello",
    "Salesforce" to "salesforce",
    "Yahoo" to "yahoo",
    "Yubico" to "yubico",
    "Proton" to "proton",
    "Fastmail" to "fastmail",
    "DuckDuckGo" to "duckduckgo",
    "Raspberry Pi" to "raspberrypi",
    "GitLab" to "gitlab",
    "Coinbase" to "coinbase",
    "Binance" to "binance",
    "Adobe" to "adobe",
    "Figma" to "figma",
    "Steam" to "steam",
    "PayPal" to "paypal",
    "Apple" to "apple"
)

fun iconSlugForIssuer(issuer: String): String? {
    val normalizedIssuer = issuer.lowercase()
    return ICON_MAP.entries.firstOrNull { (name, _) ->
        normalizedIssuer.contains(name.lowercase())
    }?.value
}
